### ISSUE TITLE
Undefined state

### ISSUE THREAD

**Issue by gunrunner20** [amcolash/MMM-GoogleFit#9]
Hi Andrew,

I just started to test your MMM-module :) Thanks for making it available!
Unfortunately right now it just shows 'undefined' states.
![2018-05-03 20_52_27](https://user-images.githubusercontent.com/38960053/39596843-f67c8ce0-4f13-11e8-9090-e0dcfbcc3414.png)

A little bit of background:

- I installed MM completely from scratch a few days ago for my final installation (Finally finished the frame).
- I looked through the available modules, found yours, installed it.
- I "reactivated" Google Fit. Meaning I stopped using it a while ago. Which is the reason why it shows 0 for every day.
- Auth worked right away (pretty cool!). In standard config it worked fine. After changing some parameter it still worked fine:
```
startOnMonday: true,
stepGoal: 8000,
innerThickness: 0.9
```
- After I started using Google Fit again (having more than 0 steps on the first day, and the others still left 0) the modules started to show the gibberish in the screenshot.
The MM html looks like the following:
![2018-05-03 21_01_00](https://user-images.githubusercontent.com/38960053/39597268-22dc9c84-4f15-11e8-90d9-c122d488e8eb.png)

Here another view from my google fit account
![2018-05-03 21_01_50](https://user-images.githubusercontent.com/38960053/39597314-4523fa3a-4f15-11e8-8726-bbe906322fb1.png)

I assume the it'll start working after I have data for every of the last 7 days. Still, this is just and educated guess.
Just wanted to let you know that there may be an issue with the marginals.
Thx :)
Marc

**Comment by justjim1220** [comment]
Mine is doing the same thing!

![screenshot 10](https://user-images.githubusercontent.com/27590633/39606312-6f68a8d8-4efa-11e8-919d-eaad525ccd54.png)

![screenshot_20180503-175113](https://user-images.githubusercontent.com/27590633/39606484-54a90848-4efb-11e8-81c6-581abfbff29f.png)

and I don't have 0 days.

and I start on Sunday.

Any ideas how to fix this would be great!

**Comment by cyberdie** [comment]
Same problem here.
![img_20180504_135646-01](https://user-images.githubusercontent.com/19409041/39626787-af359634-4fa3-11e8-99c3-db5fed0df754.jpeg)

**Comment by justjim1220** [comment]
I don't have that error message...

**Comment by justjim1220** [comment]
Working correctly today... 😏😏😏

**Comment by amcolash** [comment]
First as a heads up: I just moved from Madison to Seattle - so I have been AFK for a few days now. Now that I am back in the dev groove, let's get down to it...

It looks like google is providing weird amounts of data for some users (it should be sunday-saturday or monday-sunday). The error that @cyberdie provided gives an insight into that.

At this point in time, I am not entirely sure what the issue is - though I have a feeling of what could be a possible bug (has to do with how I am getting the start/end date range). For now, I am going to add in some safety checks and do some testing.

If this does show up for anyone in the future, let's re-open this issue.

**Comment by amcolash** [comment]
Update: With some testing, I found the bug.

Short version, it is fixed and only happens sometimes at the end of the month.
You will need to update: `$ cd MagicMirror/modules/MMM-GoogleFit` followed by `$ git pull`.

Long version: At the end of the month (like this past month), the calendar looked like this (starting on Sunday):
S   M T W T F S
29 30 1 2 3 4 5

Notice how the month changes between the start and end of the week. In my code, I was saying _roughly_:
- Make a new `Date` set to now.
- Set the start date date (i.e. the 29th) to the beginning of the week - *MAY ROLL BACK MONTH*.
- Make a new `Date` set to now.
- Set the end date date to 7 days after the start date.

On paper, this makes a whole lot of sense. *HOWEVER*, let me explain the break down and show the state (assuming this was run May 2):
- StartDate = Now = May 2 @ 12:30
- StartDate = WeekStart = April 29 @ 0:00
- EndDate = Now = May 2 @ 12:30
- EndDate = StartDate(Date, not month) + 6 = May 29 + 6 = May 31 @ 0:00

Soooo, long story short - it was getting a month of data because of a dumb error on my part. The fix is simple, just set the end date equal to the start date before the +6 day math.

I added in a safety check to prevent this issue even if the dates are wrong (by capping the number of days created).

If anyone is interested more in how this all works just let me know. Software bugs are always dumb and complicated, but it is always fun to explain how things blow up!

**Comment by cyberdie** [comment]
@amcolash It looks like the "month's change" problem is not solved.
Since yesterday (thursday) my module is showing as attached.
![2018-06-01 14 04 39](https://user-images.githubusercontent.com/19409041/40840044-53c56014-65a5-11e8-95d6-260573a7ccd7.jpg)
As you can see, there is data for tomorrow and sunday.
It seems like the data is from the past...

My config:

`config: {
				debug: false,
				stepGoal: 8000,
				startOnMonday: true,
				stepCountLabel: true,
				colors: ["#EEEEEE", "#F4511E", "#9CCC65", "#5E35B1", "#FFB300", "#F4511E"],
				updateInterval: 30
				// If desired
				}`

**Comment by amcolash** [comment]
I tried to fix this issue - again. Yikes, this is tough. Tried with a day earlier this week before/after and things looked like they were finally working. Next month, another test :wink:

**Comment by cyberdie** [comment]
Thank you @amcolash .
It looks fine right now!
![2018-06-04 09 27 00](https://user-images.githubusercontent.com/19409041/40903977-820df07c-67d9-11e8-82cb-f4666d38b87c.jpg)
